spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    changelog: classpath:/db/changelog/db.changelog-master.xml
#  profiles:
#    active: local